name: rick_morty_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  graphql_flutter: ^5.1.2
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.18.6
  auto_route: ^8.0.3
  google_fonts: ^4.0.4
  easy_localization: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  freezed: ^2.5.1
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  mockito: ^5.4.4
  riverpod_test: ^0.1.4
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
