name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_LINK: ${{ secrets.LINK }}
          file_name: .env
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze
      - name: Launch tests
        run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_LINK: ${{ secrets.LINK }}
          file_name: .env
      - name: Install project dependencies
        run: flutter pub get
      - name: Clean
        run: flutter clean
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build
        run: flutter build ios --release --no-codesign

  build_android:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_LINK: ${{ secrets.LINK }}
          file_name: .env
      - name: Install project dependencies
        run: flutter pub get
      - name: Clean
        run: flutter clean
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build
        run: flutter build apk
